pull_request_rules:
  - name: auto-merge
    description: >
      Automatic merge of PRs to main on approval with passing checks
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=Linting and Formatting
      - check-success=Secret Scanning
      - "#changes-requested-reviews-by=0"
      - -draft
      - -conflict
      - label!=do-not-merge
      - label!=needs-rebase

    actions:
      merge:
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}

          {% for user in approved_reviews_by %}
          Approved-by: {{ user }}
          {% endfor %}

  - name: ping author on conflicts and add 'needs-rebase' label
    conditions:
      - conflict
      - -closed
    actions:
      label:
        add:
          - needs-rebase
      comment:
        message: >
          This pull request has merge conflicts that must be resolved before it
          can be merged. @{{author}} please rebase it.
          https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

  - name: remove 'needs-rebase' label when conflict is resolved
    conditions:
      - -conflict
      - -closed
    actions:
      label:
        remove:
          - needs-rebase

  - name: mark pull requests as stale after 60 days
    conditions:
      - updated-at<60 days ago
      - label!=work-in-progress
      - label!=blocked
      - label!=do-not-close
      - -draft
      - -closed
    actions:
      comment:
        message: |
          This PR has been automatically marked as stale because it has not had
          recent activity for 60 days. It will be closed in 30 days if no further
          activity occurs.

          If this PR is still relevant, please:
          - Rebase/merge with the latest main branch
          - Address any review comments
          - Add a comment to keep it active

          Thank you for your contributions!
      label:
        add:
          - stale

  - name: close stale pull requests after 90 days
    conditions:
      - updated-at<90 days ago
      - label=stale
      - label!=work-in-progress
      - label!=blocked
      - label!=do-not-close
      - -closed
    actions:
      close:
        message: |
          This PR was automatically closed due to inactivity.
          If you'd like to continue this work, please reopen the PR or create a new one.

  - name: remove stale label when PR has activity
    conditions:
      - label=stale
      - -closed
    actions:
      label:
        remove:
          - stale
